### ISSUE TITLE
User check status of their signup

### ISSUE THREAD

**Issue by MissBizz** [ESORaidplanner/ESORaidplanner-discord#21]
!status (or similar command) for the user to check their status within the event.

Example: !status [event id]
Bot: MissBizz you are currently signed up as Magicka DPS Templar, and your signup has been confirmed.

Allows a user to check if they signed up, remember what they signed up as, and know if they are confirmed or set as backup.

**Comment by wayfarerx** [comment]
I have this ready to go in the bot on a local feature branch.

**Comment by wayfarerx** [comment]
Implemented in cee41a6a9efa9965cfda084cd8e7194a8abf7005.

**Comment by Woeler** [comment]
Merged to master https://github.com/ESORaidplanner/ESORaidplanner-discord/commit/20af75c239810bdc44085dd7f6826a45b2443657
