### ISSUE TITLE
Create !signups [event_id] command

### ISSUE THREAD

**Issue by Woeler** [ESORaidplanner/ESORaidplanner-discord#3]
A command that lists all the signups in a Discords embeds structure.

Endpoint will become `/api/discord/signups`

Will return an embeds structure (json) for Discord. Bot does not need to do structuring, just needs to forward.

Reacts to `!signups [event_id]` and `!roster [event_id]`

**Comment by wayfarerx** [comment]
I have this implemented in a local feature branch, but I fear that we'll have the same embeds structure work to do as in #5.

**Comment by wayfarerx** [comment]
Implemented in de3358d69e4728a5cb13636f12e60a6851569104.
