### ISSUE TITLE
The `!help` info for the `!signup "PRESET"` command is incorrect.

### ISSUE THREAD

**Issue by wayfarerx** [ESORaidplanner/ESORaidplanner-discord#33]
Currently says:
  !signup "[character preset name]"

Should be:
  !signup [event_id] "[character preset name]"

**Comment by Woeler** [comment]
Fixed https://github.com/ESORaidplanner/ESORaidplanner/tree/2a4fa5c8ad878ba10f4364d44236f5110da4d1fd
