### ISSUE TITLE
Get list of available channels via HTTP request

### ISSUE THREAD

**Issue by Woeler** [ESORaidplanner/ESORaidplanner-discord#4]
Get a list of all read/write enabled channels for the bot in a particular server. Discord server LONG will be given as parameter. Should return JSON array `channel_long => channel_name`.

**Comment by wayfarerx** [comment]
Resolved in 1b370c6.

**Comment by wayfarerx** [comment]
ADDENDUM: you call this by sending an HTTP GET request to the embedded server with the path "/channels/<discord_server_id>".
