### ISSUE TITLE
Add "stamina" as a valid role argument

### ISSUE THREAD

**Issue by jevuu** [ESORaidplanner/ESORaidplanner-discord#48]
role.js doesn't have "stamina" as an option for stamina damage dealer role. I think it should be added for consistency and to minimize confusion because magicka DDs can signup using:
`!signup 12345 sorc magicka` 
(or more often with `!signup 12345 sorc magicka dd` not knowing that the bot ignores " dd")
Meanwhile stamina DDs will encounter errors using:
`!signup 12345 sorc stamina`

**Comment by Woeler** [comment]
Done.
