### ISSUE TITLE
Change !help and !commands to embeds structure

### ISSUE THREAD

**Issue by Woeler** [ESORaidplanner/ESORaidplanner-discord#5]
Will return embeds structure, should then look like this. Will be JSON, bot only needs to forward it.

![image](https://i.gyazo.com/1aaee9178c3e1986c46ad98b79925947.png)

**Comment by wayfarerx** [comment]
So the library I'm using might not accept JSON piped through for embeds. I tried to get it to and was unsuccessful. If you have example JSON you want to try you can use http://localhost:7224/push to try it out, it will send whatever you enter directly to the specified channel. I think I might have to parse & reconstitute the JSON on my end though (which can be done without too much fuss).
