### ISSUE TITLE
Users should be able to sign up with presets.

### ISSUE THREAD

**Issue by wayfarerx** [ESORaidplanner/ESORaidplanner-discord#6]
Maybe just `!signup <event> "Heals-with-Song"`

(Heals-with-Song is my preset magplar healer.)

**Comment by wayfarerx** [comment]
I have this done in a local branch, it requires a bit of flexibility on the part of `/api/discord/signup` however.

Normally it would post { "event_id" -> event, "class" -> class, "role" -> role }

Now it can also post { "event_id" -> event, "preset" -> preset }

I can pull this out to another endpoint if that makes it easier. I'd really like to see this in 1.1.

**Comment by wayfarerx** [comment]
Implemented in 43552ab14c174dcaa20f8e59fd5260ce0ac42641.

**Comment by Woeler** [comment]
This can be done, present must then be a string, which exactly matches the name of the preset. However, how are you going to handle this if there are spaces in the name of the preset?

**Comment by wayfarerx** [comment]
My current implementation requires that the preset name is quoted but I also want to support unquoted single words.
